code --install-extension Angular.ng-template
code --install-extension Arjun.swagger-viewer
code --install-extension bashmish.es6-string-css
code --install-extension BazelBuild.vscode-bazel
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension dbaeumer.vscode-eslint
code --install-extension dotenv.dotenv-vscode
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Monokai-Midnight
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-execution
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension hashicorp.terraform
code --install-extension jebbs.plantuml
code --install-extension johnpapa.Angular2
code --install-extension MariusAlchimavicius.json-to-ts
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-playwright.playwright
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension natewallace.angular2-inline
code --install-extension NativeScript.nativescript
code --install-extension oouo-diogo-perdigao.docthis
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-yaml
code --install-extension stylelint.vscode-stylelint
code --install-extension syler.sass-indented
code --install-extension tamasfe.even-better-toml
code --install-extension Tobermory.es6-string-html
code --install-extension Tyriar.lorem-ipsum
code --install-extension unifiedjs.vscode-mdx
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension wwwalkerrun.nativescript-ng2-snippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
