code --install-extension Angular.ng-template
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Monokai-Midnight
code --install-extension joelday.docthis
code --install-extension johnpapa.Angular2
code --install-extension mrmlnc.vscode-scss
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension PeterJausovec.vscode-docker
code --install-extension quicktype.quicktype
code --install-extension robertohuertasm.vscode-icons
code --install-extension robinbentley.sass-indented
code --install-extension shinnn.stylelint
code --install-extension Telerik.nativescript
code --install-extension Tobermory.es6-string-html
code --install-extension Tyriar.lorem-ipsum
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.change-case
code --install-extension wwwalkerrun.nativescript-ng2-snippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
