code --install-extension Angular.ng-template
code --install-extension Arjun.swagger-viewer
code --install-extension bashmish.es6-string-css
code --install-extension bungcip.better-toml
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Monokai-Midnight
code --install-extension johnpapa.Angular2
code --install-extension MariusAlchimavicius.json-to-ts
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension oouo-diogo-perdigao.docthis
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-yaml
code --install-extension silvenon.mdx
code --install-extension stylelint.vscode-stylelint
code --install-extension syler.sass-indented
code --install-extension Telerik.nativescript
code --install-extension Tobermory.es6-string-html
code --install-extension Tyriar.lorem-ipsum
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.change-case
code --install-extension wwwalkerrun.nativescript-ng2-snippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
